/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gamecongklak.Frame;

import com.mycompany.gamecongklak.Class.Congklak;
import com.mycompany.gamecongklak.Class.GameResult;
import com.mycompany.gamecongklak.Class.Player;
import com.mycompany.gamecongklak.Class.PlayerOne;
import com.mycompany.gamecongklak.Class.PlayerTwo;

/**
 *
 * @author user
 */
public class CongklakFrame extends javax.swing.JFrame {
    /**
     * Variable for CongklakFrame
     */
    private Congklak congklak;
    
    
    /**
     * Creates new form CongklakFrame
     */
    public CongklakFrame(PlayerOne player1, PlayerTwo player2) {
        initComponents();
        congklak = new Congklak(player1, player2, player1.getName());
        jLabelNamePlayer1.setText(player1.getName());
        jLabelNamePlayer2.setText(player2.getName());
        updateButton();
        updateEnabledButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jLabelHouse1 = new javax.swing.JLabel();
        jButtonHole7Player1 = new javax.swing.JButton();
        jButtonHole1Player2 = new javax.swing.JButton();
        jButtonHole6Player1 = new javax.swing.JButton();
        jButtonHole2Player2 = new javax.swing.JButton();
        jButtonHole3Player2 = new javax.swing.JButton();
        jButtonHole5Player1 = new javax.swing.JButton();
        jButtonHole4Player1 = new javax.swing.JButton();
        jButtonHole4Player2 = new javax.swing.JButton();
        jButtonHole5Player2 = new javax.swing.JButton();
        jButtonHole3Player1 = new javax.swing.JButton();
        jButtonHole2Player1 = new javax.swing.JButton();
        jButtonHole6Player2 = new javax.swing.JButton();
        jButtonHole1Player1 = new javax.swing.JButton();
        jButtonHole7Player2 = new javax.swing.JButton();
        jLabelHouse2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelNamePlayer1 = new javax.swing.JLabel();
        jLabelNamePlayer2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelHouse1.setText("jLabel1");

        jButtonHole7Player1.setText("jButton1");
        jButtonHole7Player1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHole7Player1ActionPerformed(evt);
            }
        });

        jButtonHole1Player2.setText("jButton1");
        jButtonHole1Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHole1Player2ActionPerformed(evt);
            }
        });

        jButtonHole6Player1.setText("jButton1");
        jButtonHole6Player1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHole6Player1ActionPerformed(evt);
            }
        });

        jButtonHole2Player2.setText("jButton1");
        jButtonHole2Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHole2Player2ActionPerformed(evt);
            }
        });

        jButtonHole3Player2.setText("jButton1");
        jButtonHole3Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHole3Player2ActionPerformed(evt);
            }
        });

        jButtonHole5Player1.setText("jButton1");
        jButtonHole5Player1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHole5Player1ActionPerformed(evt);
            }
        });

        jButtonHole4Player1.setText("jButton1");
        jButtonHole4Player1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHole4Player1ActionPerformed(evt);
            }
        });

        jButtonHole4Player2.setText("jButton1");
        jButtonHole4Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHole4Player2ActionPerformed(evt);
            }
        });

        jButtonHole5Player2.setText("jButton1");
        jButtonHole5Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHole5Player2ActionPerformed(evt);
            }
        });

        jButtonHole3Player1.setText("jButton1");
        jButtonHole3Player1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHole3Player1ActionPerformed(evt);
            }
        });

        jButtonHole2Player1.setText("jButton1");
        jButtonHole2Player1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHole2Player1ActionPerformed(evt);
            }
        });

        jButtonHole6Player2.setText("jButton1");
        jButtonHole6Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHole6Player2ActionPerformed(evt);
            }
        });

        jButtonHole1Player1.setText("jButton1");
        jButtonHole1Player1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHole1Player1ActionPerformed(evt);
            }
        });

        jButtonHole7Player2.setText("jButton1");
        jButtonHole7Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHole7Player2ActionPerformed(evt);
            }
        });

        jLabelHouse2.setText("jLabel1");

        jLabel3.setText("Turn");

        jLabel4.setText("Turn");

        jLabelNamePlayer1.setText("jLabel1");

        jLabelNamePlayer2.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNamePlayer1)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonHole7Player1)
                                        .addGap(83, 83, 83)
                                        .addComponent(jButtonHole1Player2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonHole6Player1)
                                        .addGap(83, 83, 83)
                                        .addComponent(jButtonHole2Player2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonHole5Player1)
                                        .addGap(83, 83, 83)
                                        .addComponent(jButtonHole3Player2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonHole3Player1)
                                        .addGap(83, 83, 83)
                                        .addComponent(jButtonHole5Player2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonHole2Player1)
                                        .addGap(83, 83, 83)
                                        .addComponent(jButtonHole6Player2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonHole1Player1)
                                        .addGap(83, 83, 83)
                                        .addComponent(jButtonHole7Player2)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonHole4Player1)
                                .addGap(83, 83, 83)
                                .addComponent(jButtonHole4Player2)
                                .addGap(37, 37, 37)
                                .addComponent(jLabelNamePlayer2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelHouse2)
                            .addComponent(jLabelHouse1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelHouse1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHole7Player1)
                    .addComponent(jButtonHole1Player2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHole6Player1)
                    .addComponent(jButtonHole2Player2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHole5Player1)
                    .addComponent(jButtonHole3Player2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHole4Player1)
                    .addComponent(jButtonHole4Player2)
                    .addComponent(jLabelNamePlayer1)
                    .addComponent(jLabelNamePlayer2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHole3Player1)
                    .addComponent(jButtonHole5Player2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHole2Player1)
                    .addComponent(jButtonHole6Player2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHole1Player1)
                    .addComponent(jButtonHole7Player2))
                .addGap(18, 18, 18)
                .addComponent(jLabelHouse2)
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void updateButton(){
        Player player1 = congklak.getPlayer1();
        Player player2 = congklak.getPlayer2();
        jButtonHole1Player1.setText(Integer.toString(player1.getHole(0)));
        jButtonHole1Player2.setText(Integer.toString(player2.getHole(0)));
        jButtonHole2Player1.setText(Integer.toString(player1.getHole(1)));
        jButtonHole2Player2.setText(Integer.toString(player2.getHole(1)));
        jButtonHole3Player1.setText(Integer.toString(player1.getHole(2)));
        jButtonHole3Player2.setText(Integer.toString(player2.getHole(2)));
        jButtonHole4Player1.setText(Integer.toString(player1.getHole(3)));
        jButtonHole4Player2.setText(Integer.toString(player2.getHole(3)));
        jButtonHole5Player1.setText(Integer.toString(player1.getHole(4)));
        jButtonHole5Player2.setText(Integer.toString(player2.getHole(4)));
        jButtonHole6Player1.setText(Integer.toString(player1.getHole(5)));
        jButtonHole6Player2.setText(Integer.toString(player2.getHole(5)));
        jButtonHole7Player1.setText(Integer.toString(player1.getHole(6)));
        jButtonHole7Player2.setText(Integer.toString(player2.getHole(6)));
        jLabelHouse1.setText(Integer.toString(player1.getHouse()));
        jLabelHouse2.setText(Integer.toString(player2.getHouse()));
    }
    
    private void updateEnabledButton(){
        Player player1 = congklak.getPlayer1();
        Player player2 = congklak.getPlayer2();
        jButtonHole1Player1.setEnabled(player1.isTurn());
        jButtonHole1Player2.setEnabled(player2.isTurn());
        jButtonHole2Player1.setEnabled(player1.isTurn());
        jButtonHole2Player2.setEnabled(player2.isTurn());
        jButtonHole3Player1.setEnabled(player1.isTurn());
        jButtonHole3Player2.setEnabled(player2.isTurn());
        jButtonHole4Player1.setEnabled(player1.isTurn());
        jButtonHole4Player2.setEnabled(player2.isTurn());
        jButtonHole5Player1.setEnabled(player1.isTurn());
        jButtonHole5Player2.setEnabled(player2.isTurn());
        jButtonHole6Player1.setEnabled(player1.isTurn());
        jButtonHole6Player2.setEnabled(player2.isTurn());
        jButtonHole7Player1.setEnabled(player1.isTurn());
        jButtonHole7Player2.setEnabled(player2.isTurn());
    }
    
    private void disableAllButton(){
        jButtonHole1Player1.setEnabled(false);
        jButtonHole1Player2.setEnabled(false);
        jButtonHole2Player1.setEnabled(false);
        jButtonHole2Player2.setEnabled(false);
        jButtonHole3Player1.setEnabled(false);
        jButtonHole3Player2.setEnabled(false);
        jButtonHole4Player1.setEnabled(false);
        jButtonHole4Player2.setEnabled(false);
        jButtonHole5Player1.setEnabled(false);
        jButtonHole5Player2.setEnabled(false);
        jButtonHole6Player1.setEnabled(false);
        jButtonHole6Player2.setEnabled(false);
        jButtonHole7Player1.setEnabled(false);
        jButtonHole7Player2.setEnabled(false);
    }
    
    private void jButtonHole6Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHole6Player2ActionPerformed
        // TODO add your handling code here:
        congklak.moveBeans(5, congklak.getPlayer_turn());
        updateButton();
        updateEnabledButton();
        congklak.checkEmpty();
        System.out.println(congklak.checkEnd());
        if (congklak.checkEnd()){
            GameResult gr = congklak.GenerateResult();
            disableAllButton();
            Result r = new Result(gr);
            r.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonHole6Player2ActionPerformed

    private void jButtonHole1Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHole1Player2ActionPerformed
        // TODO add your handling code here:
        congklak.moveBeans(0, congklak.getPlayer_turn());
        updateButton();
        updateEnabledButton();
        congklak.checkEmpty();
        System.out.println(congklak.checkEnd());
        if (congklak.checkEnd()){
            GameResult gr = congklak.GenerateResult();
            disableAllButton();
            Result r = new Result(gr);
            r.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonHole1Player2ActionPerformed

    private void jButtonHole2Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHole2Player2ActionPerformed
        // TODO add your handling code here:
        congklak.moveBeans(1, congklak.getPlayer_turn());
        updateButton();
        updateEnabledButton();
        congklak.checkEmpty();
        System.out.println(congklak.checkEnd());
        if (congklak.checkEnd()){
            GameResult gr = congklak.GenerateResult();
            disableAllButton();
            Result r = new Result(gr);
            r.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonHole2Player2ActionPerformed

    private void jButtonHole3Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHole3Player2ActionPerformed
        // TODO add your handling code here:
        congklak.moveBeans(2, congklak.getPlayer_turn());
        updateButton();
        updateEnabledButton();
        congklak.checkEmpty();
        System.out.println(congklak.checkEnd());
        if (congklak.checkEnd()){
            GameResult gr = congklak.GenerateResult();
            disableAllButton();
            Result r = new Result(gr);
            r.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonHole3Player2ActionPerformed

    private void jButtonHole4Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHole4Player2ActionPerformed
        // TODO add your handling code here:
        congklak.moveBeans(3, congklak.getPlayer_turn());
        updateButton();
        updateEnabledButton();
        congklak.checkEmpty();
        System.out.println(congklak.checkEnd());
        if (congklak.checkEnd()){
            GameResult gr = congklak.GenerateResult();
            disableAllButton();
            Result r = new Result(gr);
            r.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonHole4Player2ActionPerformed

    private void jButtonHole5Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHole5Player2ActionPerformed
        // TODO add your handling code here:
        congklak.moveBeans(4, congklak.getPlayer_turn());
        updateButton();
        updateEnabledButton();
        congklak.checkEmpty();
        System.out.println(congklak.checkEnd());
        if (congklak.checkEnd()){
            GameResult gr = congklak.GenerateResult();
            disableAllButton();
            Result r = new Result(gr);
            r.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonHole5Player2ActionPerformed

    private void jButtonHole7Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHole7Player2ActionPerformed
        // TODO add your handling code here:
        congklak.moveBeans(6, congklak.getPlayer_turn());
        updateButton();
        updateEnabledButton();
        congklak.checkEmpty();
        System.out.println(congklak.checkEnd());
        if (congklak.checkEnd()){
            GameResult gr = congklak.GenerateResult();
            disableAllButton();
            Result r = new Result(gr);
            r.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonHole7Player2ActionPerformed

    private void jButtonHole1Player1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHole1Player1ActionPerformed
        // TODO add your handling code here:
        congklak.moveBeans(0, congklak.getPlayer_turn());
        updateButton();
        updateEnabledButton();
        congklak.checkEmpty();
        System.out.println(congklak.checkEnd());
        if (congklak.checkEnd()){
            GameResult gr = congklak.GenerateResult();
            disableAllButton();
            Result r = new Result(gr);
            r.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonHole1Player1ActionPerformed

    private void jButtonHole2Player1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHole2Player1ActionPerformed
        // TODO add your handling code here:
        congklak.moveBeans(1, congklak.getPlayer_turn());
        updateButton();
        updateEnabledButton();
        congklak.checkEmpty();
        System.out.println(congklak.checkEnd());
        if (congklak.checkEnd()){
            GameResult gr = congklak.GenerateResult();
            disableAllButton();
            Result r = new Result(gr);
            r.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonHole2Player1ActionPerformed

    private void jButtonHole3Player1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHole3Player1ActionPerformed
        // TODO add your handling code here:
        congklak.moveBeans(2, congklak.getPlayer_turn());
        updateButton();
        updateEnabledButton();
        congklak.checkEmpty();
        System.out.println(congklak.checkEnd());
        if (congklak.checkEnd()){
            GameResult gr = congklak.GenerateResult();
            disableAllButton();
            Result r = new Result(gr);
            r.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonHole3Player1ActionPerformed

    private void jButtonHole4Player1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHole4Player1ActionPerformed
        // TODO add your handling code here:
        congklak.moveBeans(3, congklak.getPlayer_turn());
        updateButton();
        updateEnabledButton();
        congklak.checkEmpty();
        System.out.println(congklak.checkEnd());
        if (congklak.checkEnd()){
            GameResult gr = congklak.GenerateResult();
            disableAllButton();
            Result r = new Result(gr);
            r.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonHole4Player1ActionPerformed

    private void jButtonHole5Player1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHole5Player1ActionPerformed
        // TODO add your handling code here:
        congklak.moveBeans(4, congklak.getPlayer_turn());
        updateButton();
        updateEnabledButton();
        congklak.checkEmpty();
        System.out.println(congklak.checkEnd());
        if (congklak.checkEnd()){
            GameResult gr = congklak.GenerateResult();
            disableAllButton();
            Result r = new Result(gr);
            r.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonHole5Player1ActionPerformed

    private void jButtonHole6Player1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHole6Player1ActionPerformed
        // TODO add your handling code here:
        congklak.moveBeans(5, congklak.getPlayer_turn());
        updateButton();
        updateEnabledButton();
        congklak.checkEmpty();
        System.out.println(congklak.checkEnd());
        if (congklak.checkEnd()){
            GameResult gr = congklak.GenerateResult();
            disableAllButton();
            Result r = new Result(gr);
            r.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonHole6Player1ActionPerformed

    private void jButtonHole7Player1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHole7Player1ActionPerformed
        // TODO add your handling code here:
        congklak.moveBeans(6, congklak.getPlayer_turn());
        updateButton();
        updateEnabledButton();
        congklak.checkEmpty();
        System.out.println(congklak.checkEnd());
        if (congklak.checkEnd()){
            GameResult gr = congklak.GenerateResult();
            disableAllButton();
            Result r = new Result(gr);
            r.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonHole7Player1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CongklakFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CongklakFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CongklakFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CongklakFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CongklakFrame(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHole1Player1;
    private javax.swing.JButton jButtonHole1Player2;
    private javax.swing.JButton jButtonHole2Player1;
    private javax.swing.JButton jButtonHole2Player2;
    private javax.swing.JButton jButtonHole3Player1;
    private javax.swing.JButton jButtonHole3Player2;
    private javax.swing.JButton jButtonHole4Player1;
    private javax.swing.JButton jButtonHole4Player2;
    private javax.swing.JButton jButtonHole5Player1;
    private javax.swing.JButton jButtonHole5Player2;
    private javax.swing.JButton jButtonHole6Player1;
    private javax.swing.JButton jButtonHole6Player2;
    private javax.swing.JButton jButtonHole7Player1;
    private javax.swing.JButton jButtonHole7Player2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelHouse1;
    private javax.swing.JLabel jLabelHouse2;
    private javax.swing.JLabel jLabelNamePlayer1;
    private javax.swing.JLabel jLabelNamePlayer2;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables
}
